# -*- coding: utf-8 -*-
"""
上游档案库
==========
中转路由引擎的燃料。每条记录描述一个「可被调用的上游」：

  endpoint  实际 API 根
  protocol  openai / anthropic / gemini / qwen / zhipu
  auth      认证方式
  free      免费额度描述
  models    已知可用模型

分四类：
  gateway   本地网关（工作区里的 7 个）
  relay     公益中转站（OpenAI 兼容）
  official  官方平台（自有 Key，直连）
"""

VERIFIED_AT = "2026-10-04"

# 实测记录（2026-10-04）：用假 Key 打过去，返回 401/200 即端点真实存在；
# 返回 404 才算不存在。下表里所有 base + path 都经过这一轮实测。
#   智谱 GLM      open.bigmodel.cn/api/paas/v4/models          → 401 ✅
#   智谱 coding   open.bigmodel.cn/api/coding/paas/v4/models   → 401 ✅
#   通义千问      dashscope.aliyuncs.com/compatible-mode/v1/models → 401 ✅
#   DeepSeek      api.deepseek.com/models                      → 401 ✅
#   Kimi          api.moonshot.cn/v1/models                   → 401 ✅
#   阶跃星辰      api.stepfun.com/v1/chat/completions          → 401 ✅
#   百度千帆      qianfan.baidubce.com/v2/chat/completions     → 401 ✅
#   讯飞星火      spark-api.xf-yun.com/v1/chat/completions     → 401 ✅（HMAC 签名）
#   火山方舟      ark.cn-beijing.volces.com/api/v3/models      → 401 ✅
#   百川          api.baichuan-ai.com/v1/chat/completions      → 401 ✅
#   MiniMax       api.minimax.chat/v1/text/chatcompletion_v2   → 200 ✅
#   商汤          api.sensenova.cn/v1/llm/chat/completions     → 404 ❌（路径不对，未收录）

# ================================================================= 本地网关
GATEWAYS = [
    {
        "id": "wb-gateway",
        "name": "WorkBuddy Local Gateway",
        "kind": "exe",
        "file": "workbuddy-gateway-windows-1.29.6.exe",
        "version": "1.29.6",
        "arch": "x86_64",
        "lang": "Go",
        "size": 9388544,
        "endpoint": "http://127.0.0.1:8317/v1",
        "protocol": "openai",
        "auth": "bearer",
        "auth_default": "admin",
        "managed": True,          # 由面板托管进程
        "multi_account": True,    # 多账号池轮询 + 429 自动冷却
        "upstream": ["copilot.tencent.com", "www.codebuddy.cn", "api.trae.cn"],
        "free": "账号自带额度；每日 09:00 自动签到、10:00 成长任务",
        "capabilities": {
            "chat": True, "stream": True, "vision": False, "tools": True,
            "responses": True, "anthropic": True, "token_count": True,
        },
        "endpoints": [
            "/v1/chat/completions", "/v1/models", "/v1/responses", "/v1/messages",
            "/admin/api/status", "/admin/api/checkins", "/admin/api/growth",
            "/admin/api/growth/bonus", "/admin/api/growth/lottery",
            "/admin/api/growth/redeem", "/admin/api/growth/makeup",
            "/admin/api/growth/travel", "/admin/api/growth/report",
            "/admin/api/usage", "/admin/api/usage/series",
            "/admin/api/models", "/admin/api/models/probe",
            "/admin/api/credentials", "/admin/api/credentials/delete",
            "/admin/api/login/start", "/admin/api/login/poll", "/admin/api/login/import",
            "/admin/api/apikeys", "/admin/api/webhooks", "/admin/api/settings",
            "/admin/api/logs", "/admin/api/setup", "/admin/api/probe",
        ],
        "builtin_schedule": {"checkin": "09:00", "growth": "10:00",
                             "cred_reload": "5s", "models_refresh": "60min",
                             "usage_retention": "90d"},
        "cooldown": {"account": 60, "model": 600},
        "note": "核心资产。唯一自带账号池轮询、定时签到、成长任务、用量统计、Webhook、"
                "模型免费/收费探测的网关",
    },
    {
        "id": "apk-trae",
        "name": "Trae / WorkBuddy 国内网关",
        "kind": "apk",
        "file": "base.apk",
        "package": "aigw.app",
        "version": "0.1.18",
        "size": 1411398,
        "sdk": "min24 / target34",
        "lang": "Kotlin + Jetpack Compose",
        "endpoint": "http://127.0.0.1:<动态>/v1",
        "protocol": "openai",
        "auth": "oauth",
        "oauth_ports": [51120, 51121],
        "managed": False,          # 手机端运行，PC 侧通过局域网访问
        "upstream": ["api.trae.cn", "api.trae.com.cn", "www.codebuddy.cn",
                     "www.workbuddy.ai", "trae-api-cn.mchost.guru",
                     "cloudcode-pa.googleapis.com", "accounts.google.com"],
        "free": "Trae 国内站积分；每日签到领积分 + 新用户任务 + 兑换码",
        "capabilities": {
            "chat": True, "stream": True, "vision": True, "tools": True,
            "responses": False, "anthropic": False, "token_count": False,
            "checkin": True, "tasks": True, "redeem": True, "usage": True,
        },
        "custom_slots": ["custom_model_claude", "custom_model_gemini",
                         "custom_model_kimi", "custom_model_gpt",
                         "custom_model_deepseek_v4", "custom_model_placeholder"],
        "endpoints": [
            "/api/v1/chat/completions", "/api/v1/models",
            "/api/v2/ug/checkin_credits/status", "/api/v2/ug/checkin_credits/claim",
            "/api/v1/onboarding/tasks", "/api/v1/onboarding/tasks/complete",
            "/api/v1/points/records", "/api/v1/points/activation",
            "/api/v1/points/redemption-codes/redeem", "/api/v1/team-points/balance",
            "/api/v2/pay/ide_user_ent_usage", "/api/v2/pay/web_user_ent_usage",
            "/api/v2/pay/user_current_entitlement_list",
            "/api/v3/trae/GetUserInfo", "/api/v3/trae/oauth/ExchangeToken",
            "/v2/billing/meter/daily-checkin", "/v2/billing/meter/get-user-resource",
        ],
        "permissions": ["INTERNET", "FOREGROUND_SERVICE", "FOREGROUND_SERVICE_SPECIAL_USE",
                        "WAKE_LOCK", "REQUEST_IGNORE_BATTERY_OPTIMIZATIONS",
                        "ACCESS_WIFI_STATE", "POST_NOTIFICATIONS", "DUMP"],
        "note": "**功能最全**：签到领积分、新用户任务、兑换码、积分流水、团队积分、"
                "权益套餐、用量账单、OAuth 换 token 全都有",
    },
    {
        "id": "apk-codebuddy",
        "name": "CodeBuddy 国际版网关",
        "kind": "apk",
        "file": "base(3).apk",
        "package": "com.joy4fire.workbuddy2api",
        "version": "1.1.0-native-international",
        "size": 1731645,
        "sdk": "min24 / target34",
        "lang": "Kotlin",
        "endpoint": "http://127.0.0.1:8788/v1",
        "port": 8788,
        "protocol": "openai+anthropic",
        "auth": "oauth",
        "managed": False,
        "upstream": ["copilot.tencent.com", "www.codebuddy.ai"],
        "free": "CodeBuddy 国际版账号额度",
        "capabilities": {
            "chat": True, "stream": True, "vision": True, "tools": True,
            "responses": True, "anthropic": True, "token_count": True,
            "checkin": False, "tasks": False, "redeem": False, "usage": False,
        },
        "endpoints": ["/v1/chat/completions", "/v1/models", "/v1/messages",
                      "/v1/messages/count_tokens", "/v1/responses"],
        "note": "**协议最全**：OpenAI + Anthropic Messages + Responses API 三通，"
                "自带 22 个模型清单 json（含 gpt-5.6-sol/terra/luna 系列）",
    },
    {
        "id": "apk-xiaohuanxiong",
        "name": "小浣熊 AI 网关",
        "kind": "apk",
        "file": "base(4).apk",
        "package": "dev.raccoon2api",
        "version": "1.15",
        "size": 981416,
        "sdk": "min24 / target34",
        "lang": "Kotlin",
        "endpoint": "http://127.0.0.1:<动态>/v1",
        "protocol": "openai",
        "auth": "cookie",
        "managed": False,
        "upstream": ["xiaohuanxiong.com"],
        "free": "登录即送积分，每日登录赠送",
        "capabilities": {
            "chat": True, "stream": True, "vision": False, "tools": False,
            "responses": False, "anthropic": False, "token_count": False,
            "checkin": True, "tasks": False, "redeem": False, "usage": True,
        },
        "endpoints": ["/v1/chat/completions", "/v1/models",
                      "/api/web/llm/v2", "/api/web/auth/v1",
                      "/api/web/auth/v1/entitlement_info",
                      "/api/web/points/v1/balance", "/api/web/points/v1/bills",
                      "/api/web/office/v3/setting_info",
                      "/api/web/desktop/v1/login/points/grant"],
        "note": "**唯一带「登录送积分」`/login/points/grant`** 的，可当每日签到用",
    },
    {
        "id": "apk-doubao",
        "name": "豆包网关",
        "kind": "apk",
        "file": "base(1).apk",
        "package": "dev.doubao2api",
        "version": "1.0.6",
        "size": 230364,
        "sdk": "min24 / target34",
        "lang": "Kotlin",
        "endpoint": "http://127.0.0.1:<动态>/v1",
        "protocol": "openai",
        "auth": "cookie",
        "managed": False,
        "upstream": ["www.doubao.com"],
        "free": "豆包 APP 免费对话额度",
        "capabilities": {
            "chat": True, "stream": True, "vision": True, "tools": False,
            "responses": False, "anthropic": False, "token_count": False,
            "image_gen": True, "checkin": False, "tasks": False,
            "redeem": False, "usage": False,
        },
        "endpoints": ["/v1/chat/completions", "/v1/models",
                      "/v1/images/generations",
                      "/alice/message/get_file_url", "/samantha/pages/upload_image"],
        "note": "**唯一带文生图** `/v1/images/generations` 的；支持图片上传 + 开机自启 + 悬浮窗",
    },
    {
        "id": "apk-yuanbao",
        "name": "腾讯元宝网关",
        "kind": "apk",
        "file": "base(5).apk",
        "package": "dev.yuanbao2api",
        "version": "1.2.0",
        "size": 167060,
        "sdk": "min24 / target34",
        "lang": "Kotlin",
        "endpoint": "http://127.0.0.1:<动态>/v1",
        "protocol": "openai",
        "auth": "cookie",
        "managed": False,
        "upstream": ["yuanbao.tencent.com"],
        "free": "元宝对话额度（消费 APP 内置广告换额度）",
        "capabilities": {
            "chat": True, "stream": True, "vision": False, "tools": False,
            "responses": False, "anthropic": False, "token_count": False,
            "checkin": False, "tasks": False, "redeem": False, "usage": False,
        },
        "endpoints": ["/v1/chat/completions", "/v1/models", "/api/getuserinfo",
                      "/api/chat/", "/api/user/agent/conversation/create"],
        "note": "把元宝 APP 变成 OpenAI 端点；带用户信息查询与会话创建",
    },
    {
        "id": "apk-go-native",
        "name": "Go 原生网关",
        "kind": "apk",
        "file": "base(2).apk",
        "package": "com.joy4fire.wb2apimobile",
        "version": "—",
        "size": 52290540,
        "sdk": "min21 / target28",
        "lang": "Go (GoMobile)",
        "endpoint": "http://127.0.0.1:<动态>",
        "protocol": "openai",
        "auth": "unknown",
        "managed": False,
        "upstream": ["—"],
        "free": "—",
        "capabilities": {"chat": True, "stream": False, "vision": False,
                         "tools": False, "responses": False, "anthropic": False,
                         "token_count": False, "checkin": False, "tasks": False,
                         "redeem": False, "usage": False},
        "endpoints": ["http://127.0.0.1:<port>"],
        "native_libs": ["lib/arm64-v8a/libgojni.so", "lib/armeabi-v7a/libgojni.so",
                        "lib/x86/libgojni.so", "lib/x86_64/libgojni.so"],
        "note": "GoMobile 编译，4 个 CPU 架构原生库，体积 50MB。上游未在 dex 中暴露，"
                "疑似占位/实验版本",
    },
]

# CodeBuddy 国际版自带模型清单（反解自 assets/codebuddy-international-models.json）
CODEBUDDY_MODELS = [
    {"id": "default-model", "name": "Auto", "credits": "x0.79",
     "ctx": 176000, "out": 24000, "vision": True, "tools": True, "reasoning": True},
    {"id": "default-model-lite", "name": "Default-Lite", "credits": "x0.67",
     "ctx": 176000, "out": 24000, "vision": True, "tools": True, "reasoning": True},
    {"id": "fast-model", "name": "Fast", "credits": "x0.34",
     "ctx": 200000, "out": 32000, "vision": True, "tools": True, "reasoning": True},
    {"id": "balanced-model", "name": "Balanced", "credits": "x0.59",
     "ctx": 256000, "out": 32000, "vision": True, "tools": True, "reasoning": True},
    {"id": "primary-model", "name": "Primary", "credits": "x3.31",
     "ctx": 272000, "out": 72000, "vision": True, "tools": True, "reasoning": True},
    {"id": "deep-model", "name": "Deep", "credits": "x3.33",
     "ctx": 176000, "out": 24000, "vision": True, "tools": True, "reasoning": False},
    {"id": "gpt-5.6-sol", "name": "GPT-5.6 Sol", "credits": "—",
     "ctx": 0, "out": 0, "vision": True, "tools": True, "reasoning": True},
    {"id": "gpt-5.6-terra", "name": "GPT-5.6 Terra", "credits": "—",
     "ctx": 0, "out": 0, "vision": True, "tools": True, "reasoning": True},
    {"id": "gpt-5.6-luna", "name": "GPT-5.6 Luna", "credits": "—",
     "ctx": 0, "out": 0, "vision": True, "tools": True, "reasoning": True},
    {"id": "gpt-5.5", "name": "GPT-5.5", "credits": "—",
     "ctx": 0, "out": 0, "vision": True, "tools": True, "reasoning": True},
    {"id": "gpt-5.4", "name": "GPT-5.4", "credits": "—",
     "ctx": 0, "out": 0, "vision": True, "tools": True, "reasoning": True},
    {"id": "gpt-5.3-codex", "name": "GPT-5.3 Codex", "credits": "—",
     "ctx": 0, "out": 0, "vision": True, "tools": True, "reasoning": True},
    {"id": "gemini-3.5-flash", "name": "Gemini 3.5 Flash", "credits": "—",
     "ctx": 1000000, "out": 0, "vision": True, "tools": True, "reasoning": False},
    {"id": "glm-5.3", "name": "GLM 5.3", "credits": "—",
     "ctx": 0, "out": 0, "vision": False, "tools": True, "reasoning": False},
    {"id": "glm-5.2", "name": "GLM 5.2", "credits": "—",
     "ctx": 0, "out": 0, "vision": False, "tools": True, "reasoning": False},
    {"id": "kimi-k3", "name": "Kimi K3", "credits": "—",
     "ctx": 0, "out": 0, "vision": False, "tools": True, "reasoning": False},
    {"id": "kimi-k2.6", "name": "Kimi K2.6", "credits": "—",
     "ctx": 0, "out": 0, "vision": False, "tools": True, "reasoning": False},
    {"id": "minimax-m3", "name": "MiniMax M3", "credits": "—",
     "ctx": 0, "out": 0, "vision": False, "tools": True, "reasoning": False},
]

# ================================================================= 公益中转站
# protocol 全为 openai 兼容；auth 分 token / cookie / password 三档
RELAYS = [
    {"name": "AnyRouter", "url": "https://anyrouter.top",
     "endpoint": "https://anyrouter.top/v1", "protocol": "openai",
     "auth": "cookie+api_user", "checkin_path": "/api/user/sign_in",
     "bonus": "注册赠 $100，签到送 $25", "models": "Claude 系 10+",
     "limit": "Linux Do 信任等级≥2", "models_hint": ["claude-sonnet-4", "claude-opus-4"]},
    {"name": "AgentRouter", "url": "https://agentrouter.org",
     "endpoint": "https://agentrouter.org/v1", "protocol": "openai",
     "auth": "cookie+api_user", "checkin_path": "/api/user/checkin",
     "bonus": "注册赠 $100，签到送 $25", "models": "Claude/GPT/GLM/DeepSeek",
     "limit": "GitHub 注册满 5 年", "models_hint": ["claude-sonnet-4", "gpt-5", "glm-5", "deepseek-v4"]},
    {"name": "PM-API", "url": "https://xn--wnup5g6so4wn.de5.net",
     "endpoint": "https://xn--wnup5g6so4wn.de5.net/v1", "protocol": "openai",
     "auth": "token", "checkin_path": None,
     "bonus": "完全免费无签到", "models": "240 个",
     "limit": "—", "models_hint": ["claude-sonnet-4", "gpt-5", "glm-5", "deepseek-v4", "gemini-3"]},
    {"name": "快跑 API", "url": "https://kuaipao.ai",
     "endpoint": "https://kuaipao.ai/v1", "protocol": "openai",
     "auth": "token", "checkin_path": "/api/user/checkin",
     "bonus": "每日签到", "models": "100+ 个",
     "limit": "—", "models_hint": ["claude-sonnet-4", "gpt-5", "glm-5", "deepseek-v4"]},
    {"name": "维云模型", "url": "https://vsllm.cc",
     "endpoint": "https://vsllm.cc/v1", "protocol": "openai",
     "auth": "token", "checkin_path": "/api/user/checkin",
     "bonus": "每日任务换额度", "models": "69 个",
     "limit": "注册无限制", "models_hint": ["claude-sonnet-4", "gpt-5", "glm-5"]},
    {"name": "New API 福利站", "url": "https://new-api.abrdns.com",
     "endpoint": "https://new-api.abrdns.com/v1", "protocol": "openai",
     "auth": "cookie+api_user", "checkin_path": "/api/user/checkin",
     "bonus": "每日福利签到", "models": "69 个",
     "limit": "Linux Do Lv1 + 注册满 1 天", "models_hint": ["claude-sonnet-4", "gpt-5"]},
    {"name": "CM-API 公益站", "url": "https://api.chengmo.cc.cd",
     "endpoint": "https://api.chengmo.cc.cd/v1", "protocol": "openai",
     "auth": "cookie+api_user", "checkin_path": "/api/user/checkin",
     "bonus": "每日签到", "models": "46 个",
     "limit": "注册无限制", "models_hint": ["claude-sonnet-4", "glm-5", "deepseek-v4"]},
    {"name": "ZeroCat", "url": "https://zero.cat",
     "endpoint": "https://zero.cat/v1", "protocol": "openai",
     "auth": "cookie+api_user", "checkin_path": "/api/user/checkin",
     "bonus": "每日签到", "models": "Claude/DS/xAI/Gemini 40 个",
     "limit": "—", "models_hint": ["claude-sonnet-4", "deepseek-v4", "gemini-3"]},
    {"name": "Huan API", "url": "https://ai.huan666.de",
     "endpoint": "https://ai.huan666.de/v1", "protocol": "openai",
     "auth": "cookie+api_user", "checkin_path": "/api/user/checkin",
     "bonus": "每日签到", "models": "17 个",
     "limit": "—", "models_hint": ["claude-sonnet-4"]},
    {"name": "可萌中转站", "url": "https://api456.me",
     "endpoint": "https://api456.me/v1", "protocol": "openai",
     "auth": "cookie+api_user", "checkin_path": "/api/user/checkin",
     "bonus": "每日签到", "models": "Claude/GPT/GLM/DS/Gemini/qwen 29",
     "limit": "注册无限制", "models_hint": ["claude-sonnet-4", "gpt-5", "gemini-3"]},
    {"name": "Token 能量站", "url": "https://factory.pub",
     "endpoint": "https://factory.pub/v1", "protocol": "openai",
     "auth": "cookie+api_user", "checkin_path": "/api/user/checkin",
     "bonus": "每日签到", "models": "20 个",
     "limit": "仅 yaohuo/github 注册", "models_hint": ["claude-sonnet-4", "glm-5"]},
    {"name": "Pomelo", "url": "https://api.67.si",
     "endpoint": "https://api.67.si/v1", "protocol": "openai",
     "auth": "cookie+api_user", "checkin_path": "/api/user/checkin",
     "bonus": "每日签到", "models": "xAI/GPT/GLM/DS 17",
     "limit": "—", "models_hint": ["gpt-5", "glm-5"]},
    {"name": "BER分公益站", "url": "https://ai.berf1.cn",
     "endpoint": "https://ai.berf1.cn/v1", "protocol": "openai",
     "auth": "cookie+api_user", "checkin_path": "/api/user/checkin",
     "bonus": "每日签到", "models": "4 个",
     "limit": "—", "models_hint": ["glm-5", "deepseek-v4"]},
    {"name": "hkai", "url": "https://share.hkai25.top",
     "endpoint": "https://share.hkai25.top/v1", "protocol": "openai",
     "auth": "cookie+api_user", "checkin_path": "/api/user/checkin",
     "bonus": "每日签到", "models": "xAI/minimax/GLM/DS 10",
     "limit": "—", "models_hint": ["minimax-m3", "glm-5"]},
    {"name": "糯喵喵 AI 驿站", "url": "https://ai.yangwj.me",
     "endpoint": "https://ai.yangwj.me/v1", "protocol": "openai",
     "auth": "cookie+api_user", "checkin_path": "/api/user/checkin",
     "bonus": "每日签到", "models": "47 个",
     "limit": "—", "models_hint": ["claude-sonnet-4", "gpt-5", "deepseek-v4"]},
    {"name": "onomeo", "url": "https://onomeo.com",
     "endpoint": "https://onomeo.com/v1", "protocol": "openai",
     "auth": "token", "checkin_path": "/api/user/checkin",
     "bonus": "签到积分：首日 5000，第 7 天起 10000/日", "models": "35 免费 + 9 付费",
     "limit": "免费账号 5h/20 次，12 RPM",
     "models_hint": ["deepseek-v4", "glm-5", "gemini-3", "qwen3"]},
    {"name": "奶昔 New API", "url": "https://newapi.naixi.net",
     "endpoint": "https://newapi.naixi.net/v1", "protocol": "openai",
     "auth": "token", "checkin_path": "/api/user/checkin",
     "bonus": "开户送 $5，签到送 1-2 刀/日", "models": "模型广场自选",
     "limit": "需奶昔 SSO 账号", "models_hint": ["claude-sonnet-4", "gpt-5"]},
]

# ================================================================= 官方免费平台
OFFICIAL = [
    # ============ 2026-10-04 实测确认存在的国内厂商（假 Key → 401 即端点真实） ============
    {"name": "DeepSeek 官方", "region": "国内",
     "endpoint": "https://api.deepseek.com", "protocol": "openai",
     "auth": "api_key", "env": "DEEPSEEK_API_KEY",
     "free": "无免费额度，但新号常有充值赠送",
     "checkin": None, "rate": "按账户",
     "models_hint": ["deepseek-chat", "deepseek-reasoner"],
     "note": "★ 工具调用支持最完整的一家（有非思考/思考双模式 + strict Beta，"
             "文档 api-docs.deepseek.com/guides/tool_calls）。"
             "实测 /models 与 /chat/completions 均返回 401 ✅"},
    {"name": "Kimi 月之暗面", "region": "国内",
     "endpoint": "https://api.moonshot.cn/v1", "protocol": "openai",
     "auth": "api_key", "env": "MOONSHOT_API_KEY",
     "free": "注册送 15 元额度",
     "checkin": None, "rate": "按账户",
     "models_hint": ["moonshot-v1-8k", "moonshot-v1-32k", "kimi-k2-turbo-preview"],
     "note": "支持 function calling（tool_calls[].{id,type,function} + tool_choice 四值，"
             "文档 platform.kimi.com/docs/api/chat）。实测 /v1/models → 401 ✅"},
    {"name": "阶跃星辰 StepFun", "region": "国内",
     "endpoint": "https://api.stepfun.com/v1", "protocol": "openai",
     "auth": "api_key", "env": "STEPFUN_API_KEY",
     "free": "新用户送额度",
     "checkin": None, "rate": "按账户",
     "models_hint": ["step-2-16k", "step-1x-medium"],
     "note": "支持 function calling。实测 /v1/chat/completions → 401 ✅"},
    {"name": "MiniMax", "region": "国内",
     "endpoint": "https://api.minimax.chat/v1", "protocol": "openai",
     "auth": "api_key", "env": "MINIMAX_API_KEY",
     "free": "新用户送 token",
     "checkin": None, "rate": "按账户",
     "models_hint": ["abab6.5s-chat", "abab5.5s-chat"],
     "note": "实测 /v1/text/chatcompletion_v2 → 200（错误码 1004 鉴权失败）✅，"
             "是本次唯一直接返回 200 的国内厂商"},
    {"name": "百川智能", "region": "国内",
     "endpoint": "https://api.baichuan-ai.com/v1", "protocol": "openai",
     "auth": "api_key", "env": "BAICHUAN_API_KEY",
     "free": "注册送额度",
     "checkin": None, "rate": "按账户",
     "models_hint": ["Baichuan4", "Baichuan4-Air"],
     "note": "支持 function calling，参数表连 messages[].tool_calls 都列了，兼容性最好。"
             "实测 /v1/chat/completions → 401 ✅"},
    {"name": "讯飞星火", "region": "国内",
     "endpoint": "https://spark-api.xf-yun.com/v1", "protocol": "openai",
     "auth": "hmac", "env": "SPARK_API_KEY",
     "free": "部分模型免费",
     "checkin": None, "rate": "按账户",
     "models_hint": ["spark-max", "spark-4.0-ultra"],
     "note": "支持工具调用但 tools 结构与其他家不同，需 tool_calls_switch:true；"
             "鉴权用 HMAC 签名（不是 Bearer）。实测 → 401 HMAC ✅"},
    {"name": "火山方舟（豆包）", "region": "国内",
     "endpoint": "https://ark.cn-beijing.volces.com/api/v3", "protocol": "openai",
     "auth": "api_key", "env": "ARK_API_KEY",
     "free": "部分模型免费额度",
     "checkin": None, "rate": "按账户",
     "models_hint": ["doubao-pro", "doubao-lite", "doubao-seed"],
     "note": "支持工具调用，模型页有逐模型「工具调用能力」勾选表，Chat + Responses 双 API。"
             "实测 /api/v3/models → 401 ✅"},
    {"name": "智谱 GLM Coding", "region": "国内",
     "endpoint": "https://open.bigmodel.cn/api/coding/paas/v4", "protocol": "openai",
     "auth": "api_key", "env": "ZHIPUAI_CODING_KEY",
     "free": "GLM Coding Plan 有免费额度",
     "checkin": None, "rate": "按账户",
     "models_hint": ["glm-4.6", "glm-4.5-air"],
     "note": "智谱面向编程场景的独立 base_url。实测 /paas/v4/models → 401 ✅"},

    {"name": "智谱 BigModel", "region": "国内",
     "endpoint": "https://open.bigmodel.cn/api/paas/v4", "protocol": "openai",
     "auth": "api_key", "env": "ZHIPUAI_API_KEY",
     "free": "GLM-4.7-Flash / GLM-4-Flash / GLM-4.6V-Flash 永久免费",
     "checkin": "每日签到送 1 万 token", "rate": "30 QPS",
     "models_hint": ["glm-4.7-flash", "glm-4-flash", "glm-4.6v-flash"],
     "note": "新用户赠 2000 万 token；国际站 api.z.ai 同源免费模型"},
    {"name": "阿里云百炼", "region": "国内",
     "endpoint": "https://dashscope.aliyuncs.com/compatible-mode/v1", "protocol": "openai",
     "auth": "api_key", "env": "DASHSCOPE_API_KEY",
     "free": "通义千问全系免费；新人 7000 万 token + 100 张生图",
     "checkin": None, "rate": "按模型",
     "models_hint": ["qwen3-max", "qwen3-plus", "qwen3-flash", "qwen3-coder-plus"],
     "note": "有效期 180 天，可开「用完即停」"},
    {"name": "百度千帆", "region": "国内",
     "endpoint": "https://qianfan.baidubce.com/v2", "protocol": "openai",
     "auth": "api_key", "env": "QIANFAN_API_KEY",
     "free": "ERNIE-Speed/Lite/Tiny 永久免费不限量；新用户 150 万 token",
     "checkin": None, "rate": "50 QPS",
     "models_hint": ["ernie-speed-8k", "ernie-lite-8k"],
     "note": "需实名认证"},
    {"name": "硅基流动 SiliconFlow", "region": "国内",
     "endpoint": "https://api.siliconflow.cn/v1", "protocol": "openai",
     "auth": "api_key", "env": "SILICONFLOW_API_KEY",
     "free": "部分模型永久免费 + 新户赠 14 元",
     "checkin": None, "rate": "按模型",
     "models_hint": ["deepseek-ai/DeepSeek-V3", "Qwen/Qwen3-32B"],
     "note": "国内直连海外模型"},
    {"name": "美团 LongCat", "region": "国内",
     "endpoint": "https://api.longcat.chat/openai/v1", "protocol": "openai",
     "auth": "api_key", "env": "LONGCAT_API_KEY",
     "free": "LongCat-2.5-Preview 资源包 + 活动赠送",
     "checkin": None, "rate": "—",
     "models_hint": ["LongCat-Flash-Chat"],
     "note": "1M 上下文 / 128K 输出"},
    {"name": "讯飞星辰 MaaS", "region": "国内",
     "endpoint": "https://spark-api-open.xf-yun.com/v1", "protocol": "openai",
     "auth": "api_key", "env": "SPARK_API_KEY",
     "free": "Qwen3-Coder-Next / Qwen3-1.7B 永久免费不限量",
     "checkin": None, "rate": "—",
     "models_hint": ["qwen3-coder-next", "qwen3-1.7b"],
     "note": "星火 X2.5 限时免费"},
    {"name": "魔搭 ModelScope", "region": "国内",
     "endpoint": "https://api-inference.modelscope.cn/v1", "protocol": "openai",
     "auth": "api_key", "env": "MODELSCOPE_API_KEY",
     "free": "3000+ 模型，魔棒兑换调用",
     "checkin": None, "rate": "动态限流",
     "models_hint": ["Qwen/Qwen3-32B"],
     "note": "需绑阿里云并实名"},
    {"name": "Google AI Studio", "region": "海外",
     "endpoint": "https://generativelanguage.googleapis.com/v1beta/openai",
     "protocol": "openai", "auth": "api_key", "env": "GEMINI_API_KEY",
     "free": "Gemini 全系免费层",
     "checkin": None, "rate": "15 RPM / 1500 RPD",
     "models_hint": ["gemini-3.5-flash", "gemini-3.5-flash-lite", "gemini-2.5-pro"],
     "note": "无需信用卡，海外最慷慨"},
    {"name": "NVIDIA NIM", "region": "海外",
     "endpoint": "https://integrate.api.nvidia.com/v1", "protocol": "openai",
     "auth": "api_key", "env": "NVIDIA_API_KEY",
     "free": "100+ 模型无限额（仅速率限制）",
     "checkin": None, "rate": "~40 RPM",
     "models_hint": ["meta/llama-3.3-70b-instruct", "qwen/qwen3-coder-480b-a35b-instruct"],
     "note": "无需信用卡"},
    {"name": "Groq", "region": "海外",
     "endpoint": "https://api.groq.com/openai/v1", "protocol": "openai",
     "auth": "api_key", "env": "GROQ_API_KEY",
     "free": "免费 tier 极低延迟",
     "checkin": None, "rate": "30 RPM / 1000 RPD",
     "models_hint": ["moonshotai/kimi-k2-instruct", "qwen/qwen3-32b"],
     "note": "最快的一档，适合自动路由的延迟优选"},
    {"name": "OpenRouter", "region": "海外",
     "endpoint": "https://openrouter.ai/api/v1", "protocol": "openai",
     "auth": "api_key", "env": "OPENROUTER_API_KEY",
     "free": "20+ free 模型，每日请求上限",
     "checkin": None, "rate": "按模型",
     "models_hint": ["deepseek/deepseek-chat-v3", "google/gemini-2.5-flash"],
     "note": "搜 free 标签筛选"},
    {"name": "Cloudflare Workers AI", "region": "海外",
     "endpoint": "https://api.cloudflare.com/client/v4/accounts/{id}/ai/run",
     "protocol": "openai", "auth": "api_key", "env": "CF_API_TOKEN",
     "free": "免费层每天 10,000 Neurons",
     "checkin": None, "rate": "—",
     "models_hint": ["@cf/meta/llama-3.1-8b-instruct"],
     "note": "边缘推理"},
    {"name": "HuggingFace", "region": "海外",
     "endpoint": "https://router.huggingface.co/v1", "protocol": "openai",
     "auth": "api_key", "env": "HF_API_KEY",
     "free": "每月 $0.10 credits",
     "checkin": None, "rate": "—",
     "models_hint": ["meta-llama/Llama-3.3-70B-Instruct"],
     "note": "模型生态最全"},
    {"name": "Cerebras", "region": "海外",
     "endpoint": "https://api.cerebras.ai/v1", "protocol": "openai",
     "auth": "api_key", "env": "CEREBRAS_API_KEY",
     "free": "$5 试用额度（需绑支付方式）",
     "checkin": None, "rate": "—",
     "models_hint": ["llama3.3-70b"],
     "note": "推理极快，适合延迟优选"},
]

# ================================================================= 开源工具
OPEN_SOURCE = [
    {"name": "New-API", "url": "https://github.com/QuantumNous/new-api",
     "desc": "国内最流行的统一网关，带签到系统 / 额度分配 / 用量看板",
     "stack": "Go + React", "role": "自建中转站"},
    {"name": "One API", "url": "https://github.com/songquanpeng/one-api",
     "desc": "38k+ Star，100+ 渠道，New-API 前身",
     "stack": "Go", "role": "自建中转站"},
    {"name": "All API Hub", "url": "https://github.com/Jekeer/all-api-hub",
     "desc": "浏览器插件，统一管理 NewAPI 站点余额/模型/密钥 + 自动签到",
     "stack": "WXT + React + TS", "role": "站点管理"},
    {"name": "newapi-ai-check-in", "url": "https://github.com/chiocai/newapi-ai-check-in",
     "desc": "NewAPI 多账号自动签到，支持 WAF / Turnstile 绕过与多种登录",
     "stack": "Python", "role": "签到脚本"},
    {"name": "FreeLLMAPI", "url": "https://github.com/Alvaro-Cintas/freellmapi",
     "desc": "聚合 14+ 家免费额度为单一 OpenAI 端点，自动故障转移",
     "stack": "Python", "role": "聚合路由"},
    {"name": "AI Proxy", "url": "https://github.com/labring/aiproxy",
     "desc": "企业级多租户网关，负载均衡 + 自动重试",
     "stack": "Go", "role": "生产网关"},
    {"name": "free-newapi 清单", "url": "https://github.com/kirito8/free-newapi",
     "desc": "公益站与免费额度平台清单，本项目数据来源，持续维护",
     "stack": "Markdown", "role": "数据源"},
    {"name": "One API Hub", "url": "https://github.com/DaemonRamble/one-api-hub",
     "desc": "轻量 Web 服务，SQLite + JWT，聚合 NewAPI 系站点签到与额度",
     "stack": "Node + Hono + React", "role": "站点管理"},
]

# ========================================== Vibe Coding 反代项目（2026-10-04 调研）
# 这批是「把某个 Vibe Coding 工具的登录凭据转成 OpenAI 兼容 API」的开源项目。
# 本机部署任何一个，就能直接作为一个上游挂进路由引擎。
# star / 更新时间来自 GitHub API 实测（见 VibeCoding与反代调研.md）。
VIBE_PROXY = [
    {
        "id": "cliproxyapi",
        "name": "CLIProxyAPI",
        "url": "https://github.com/router-for-me/CLIProxyAPI",
        "stars": 54037, "lang": "Go", "updated": "2026-10-03",
        "endpoint": "http://127.0.0.1:8317",   # 默认端口，按需改
        "protocol": ["openai", "anthropic", "gemini", "codex"],
        "auth": "oauth",
        # ★ 实测 v8.0.13（2026-10-03 下载后跑 --help 确认）：
        #   登录项只有 -kimi-login / -kimi-ai-login / -codex-login /
        #   -codex-device-login / -claude-login / -antigravity-login /
        #   -xai-login / -devin-login / -meta-login
        #   **没有 CodeBuddy，也没有 Qoder** —— 早期资料说「原生支持
        #   CodeBuddy CN/Intl」是错的，已在此更正，别再按那个去配。
        "targets": ["Kimi", "Codex(OpenAI)", "Claude", "Antigravity(Gemini)",
                    "xAI Grok", "Devin", "Meta Muse"],
        "login_flags": ["-kimi-login", "-codex-login", "-claude-login",
                        "-antigravity-login", "-xai-login", "-devin-login",
                        "-meta-login"],
        "deploy": "Go 单二进制（71 MB）",
        "checkin": False,
        "free": "取决于所挂的订阅账号",
        "note": "★ 把 CLI 订阅（Kimi Code / Codex / Claude Code / Antigravity）"
                "转成 OpenAI 兼容 API，多账号轮询 + Management API。"
                "本机已下载 v8.0.13 到 cli-proxy/。",
        "priority": 1,
    },
    {
        "id": "claude-code-router",
        "name": "claude-code-router",
        "url": "https://github.com/musistudio/claude-code-router",
        "stars": 37523, "lang": "TypeScript", "updated": "2026-09-26",
        "endpoint": "http://127.0.0.1:3456",
        "protocol": ["anthropic", "openai"],
        "auth": "multi",
        "targets": ["Claude Code", "Codex", "Kilo Code", "OpenCode",
                    "WorkBuddy", "Grok CLI", "Kimi CLI"],
        "deploy": "有 Windows/macOS/Linux 桌面版（EXE 直接下）",
        "checkin": False,
        "free": "取决于所挂的订阅账号",
        "note": "★ 上手成本最低：EXE 下载即用，一个本地端点接管 7 个 CLI。"
                "带请求日志 / resolved route / token 用量 / 成本估算。",
        "priority": 2,
    },
    {
        "id": "cockpit-tools",
        "name": "cockpit-tools",
        "url": "https://github.com/jlcodes99/cockpit-tools",
        "stars": 18612, "lang": "Rust", "updated": "2026-10-01",
        "endpoint": "",
        "protocol": ["openai"],
        "auth": "oauth",
        "targets": ["Antigravity", "Codex", "Copilot", "Windsurf", "Kiro",
                    "Cursor", "Grok CLI", "CodeBuddy", "CodeBuddy CN",
                    "Qoder", "Trae", "TRAE SOLO", "Trae CN", "Zed", "ZCode"],
        "deploy": "Rust 桌面应用（内置 CLIProxyAPI 作为 API 服务）",
        "checkin": True,
        "free": "各平台免费额度",
        "note": "★ 与本面板定位最互补：16 个 Vibe Coding 平台的切号 + 配额监控 + "
                "自动唤醒 + 多开。已带 WorkBuddy daily check-in 模块。",
        "priority": 2,
    },
    {
        "id": "trae2api-cn",
        "name": "Trae2api-cn",
        "url": "https://github.com/autumnsentiment/Trae2api-cn",
        "stars": 31, "lang": "Python", "updated": "2026-10-01",
        "endpoint": "http://127.0.0.1:8000",
        "protocol": ["openai", "responses"],
        "auth": "oauth",
        "targets": ["Trae CN", "TRAE SOLO CN"],
        "deploy": "Python / Docker，有 /v1/status 探活",
        "checkin": True,
        "free": "Trae 账号自带额度",
        "note": "★ 唯一把 checkin（签到）写进反代逻辑的国产 IDE 项目，"
                "多账号 round-robin + 网页 OAuth 登录。与面板已做的 Trae 签到同源。",
        "priority": 1,
    },
    {
        "id": "workbuddy-manager",
        "name": "workbuddy-manager",
        "url": "https://github.com/ithtelab/workbuddy-manager",
        "stars": 740, "lang": "Python", "updated": "2026-10-03",
        "endpoint": "",
        "protocol": ["openai"],
        "auth": "qrcode",
        "targets": ["腾讯 WorkBuddy / CodeBuddy"],
        "deploy": "Next.js 15 + FastAPI",
        "checkin": True,
        "free": "账号自带额度",
        "note": "★ 定时签到与保活 + 密钥分组分发 + IP/模型白名单。"
                "上游 workbuddy2api 源码随发布包分发（MIT）。",
        "priority": 1,
    },
    {
        "id": "workbuddy2api-panel",
        "name": "workbuddy2api-panel",
        "url": "https://github.com/linguo2625469/workbuddy2api-panel",
        "stars": 1798, "lang": "Go", "updated": "2026-10-01",
        "endpoint": "",
        "protocol": ["openai"],
        "auth": "qrcode",
        "targets": ["腾讯 WorkBuddy / CodeBuddy"],
        "deploy": "Go 单二进制 + Web 面板",
        "checkin": True,
        "free": "账号自带额度",
        "note": "自动完成任务中心全部积分任务，账号池 + 积分任务 + 配置热更新。"
                "任务自动化的实现思路值得直接参考。",
        "priority": 2,
    },
    {
        "id": "sub2api",
        "name": "sub2api",
        "url": "https://github.com/Wei-Shaw/sub2api",
        "stars": 43253, "lang": "Go", "updated": "2026-10-03",
        "endpoint": "",
        "protocol": ["openai"],
        "auth": "key",
        "targets": ["通用（订阅资源池化）"],
        "deploy": "Go + Docker",
        "checkin": False,
        "free": "订阅账号分摊",
        "note": "订阅资源池化 + 用户级 Key 分发 + 限速计费。"
                "new-api 已原生支持它作为渠道类型（ChannelTypeSub2API = 59）。",
        "priority": 3,
    },
    {
        "id": "windsurfapi",
        "name": "WindsurfAPI",
        "url": "https://github.com/dwgx/WindsurfAPI",
        "stars": 3058, "lang": "JavaScript", "updated": "2026-10-03",
        "endpoint": "",
        "protocol": ["openai", "anthropic", "gemini", "responses"],
        "auth": "cookie",
        "targets": ["Windsurf", "Devin Desktop"],
        "deploy": "零 npm 运行时依赖",
        "checkin": False,
        "free": "25 prompt credits/月",
        "note": "100+ 模型 → 四套标准 API。Windsurf 已改名 Devin Desktop，"
                "免费额度很少但正代成本极低。",
        "priority": 3,
    },
    {
        "id": "codex-proxy",
        "name": "codex-proxy",
        "url": "https://github.com/XxxXTeam/codex-proxy",
        "stars": 163, "lang": "Go", "updated": "2026-10-01",
        "endpoint": "",
        "protocol": ["openai", "anthropic"],
        "auth": "oauth",
        "targets": ["OpenAI Codex"],
        "deploy": "Go 单二进制",
        "checkin": False,
        "free": "Codex 订阅额度",
        "note": "Codex 代理，OpenAI + Claude 双协议，中文社区项目，"
                "可作为 CLIProxyAPI 的轻量备选。",
        "priority": 3,
    },
    {
        "id": "work-daddy",
        "name": "WorkDaddy",
        "url": "https://github.com/babygoton/WorkDaddy",
        "stars": 1665, "lang": "JavaScript", "updated": "2026-10-01",
        "endpoint": "",
        "protocol": [],
        "auth": "qrcode",
        "targets": ["WorkBuddy / CodeBuddy 桌面端"],
        "deploy": "桌面应用",
        "checkin": True,
        "free": "账号自带额度",
        "note": "签到猫猫旅行成长计划查询、多账号独立备份、跨账号会话迁移。",
        "priority": 3,
    },
    {
        "id": "all-api-hub",
        "name": "all-api-hub",
        "url": "https://github.com/qixing-jk/all-api-hub",
        "stars": 4909, "lang": "TypeScript", "updated": "2026-10-03",
        "endpoint": "",
        "protocol": [],
        "auth": "key",
        "targets": ["New-API / Sub2API 中转站"],
        "deploy": "浏览器扩展",
        "checkin": True,
        "free": "取决于中转站",
        "note": "余额用量看板 + 自动签到 + 一键导 key + 价格对比 + 健康检测。"
                "定位与本面板高度重合，其站点适配清单值得参考。",
        "priority": 2,
    },
    {
        "id": "quotio",
        "name": "quotio",
        "url": "https://github.com/nguyenphutrong/quotio",
        "stars": 4878, "lang": "Swift", "updated": "2026-10-03",
        "endpoint": "",
        "protocol": [],
        "auth": "subscription",
        "targets": ["Claude", "Gemini", "OpenAI", "Qwen", "Antigravity"],
        "deploy": "⚠ 仅 macOS 菜单栏应用，Windows 不可用",
        "checkin": False,
        "free": "订阅额度聚合",
        "note": "实时配额追踪 + 自动故障转移。功能参考价值高，但平台不符。",
        "priority": 4,
    },
]

# 已失效 / 不推荐（2026-10-04 实测），留着当反面清单避免以后再踩
VIBE_DEAD = [
    {"name": "cursor2api-go", "url": "https://github.com/gengyuhao/cursor2api-go",
     "why": "README 自写「❌ 这次倒下啦」，最后 commit 是回退无头浏览器方案（Vercel 已能检测 headless Chrome）"},
    {"name": "Roo Code", "url": "https://github.com/RooCodeInc/Roo-Code",
     "why": "2026-05-15 全部产品关停（VS Code 扩展 + Roo Cloud + Router），仓库归档只读"},
    {"name": "Continue", "url": "https://github.com/continuedev/continue",
     "why": "被 Cursor 收购，2026-06 停止独立产品线"},
    {"name": "Gemini CLI 免费层", "url": "https://github.com/google-gemini/gemini-cli",
     "why": "2026-06-18 起不再服务免费用户，官方引导改用 Antigravity CLI"},
    {"name": "Qwen Code OAuth 免费层", "url": "https://github.com/QwenLM/qwen-code",
     "why": "2026-04-15 彻底关闭（先从 1000/天砍到 100/天再关），CLI 本体仍免费开源"},
    {"name": "GitHub Models", "url": "https://github.com/github/models",
     "why": "2026-07-30 全面退役"},
    {"name": "One API", "url": "https://github.com/songquanpeng/one-api",
     "why": "未 archived 但最后 commit 停在 2026-01，实质停滞，fork 请用 new-api"},
    {"name": "讯飞 iFlyCode", "url": "https://github.com/iflycode",
     "why": "上游服务已停服"},
    {"name": "Amazon Q Developer", "url": "https://github.com/amazon-q-developer-cli",
     "why": "停止新用户免费注册"},
]


# ================================================================= 汇总视图
def all_upstreams():
    """所有可作为路由目标的上游，扁平化成统一结构"""
    out = []
    for g in GATEWAYS:
        out.append({
            "id": g["id"], "name": g["name"], "category": "gateway",
            "kind": g["kind"], "endpoint": g.get("endpoint"),
            "port": g.get("port"), "protocol": g.get("protocol"),
            "auth": g.get("auth"), "managed": g.get("managed", False),
            "free": g.get("free", ""), "note": g.get("note", ""),
            "capabilities": g.get("capabilities", {}),
            "multi_account": g.get("multi_account", False),
        })
    for r in RELAYS:
        out.append({
            "id": "relay-" + r["name"].lower().replace(" ", "-"),
            "name": r["name"], "category": "relay", "kind": "web",
            "endpoint": r["endpoint"], "protocol": r["protocol"],
            "auth": r["auth"], "managed": False,
            "free": r["bonus"], "note": r["limit"],
            "checkin_path": r.get("checkin_path"),
            "models_hint": r.get("models_hint", []),
        })
    for o in OFFICIAL:
        out.append({
            "id": "official-" + o["name"].lower().replace(" ", "-"),
            "name": o["name"], "category": "official", "kind": "web",
            "endpoint": o["endpoint"], "protocol": o["protocol"],
            "auth": o["auth"], "env": o.get("env"),
            "region": o["region"], "managed": False,
            "free": o["free"], "note": o.get("note", ""),
            "rate": o.get("rate"), "checkin": o.get("checkin"),
            "models_hint": o.get("models_hint", []),
        })
    # Vibe Coding 反代项目：本地部署后即可作为上游；未部署的 endpoint 为空
    for v in VIBE_PROXY:
        out.append({
            "id": "vibe-" + v["id"],
            "name": v["name"], "category": "vibe_proxy", "kind": "git",
            "endpoint": v.get("endpoint") or "",
            "protocol": v.get("protocol", []),
            "auth": v.get("auth", ""),
            "managed": False,
            "free": v.get("free", ""), "note": v.get("note", ""),
            "repo": v["url"], "stars": v.get("stars", 0),
            "lang": v.get("lang", ""), "updated": v.get("updated", ""),
            "targets": v.get("targets", []), "deploy": v.get("deploy", ""),
            "checkin": bool(v.get("checkin")),
            "priority": v.get("priority", 3),
            "deployed": False,
        })
    return out


def stats():
    g = GATEWAYS
    return {
        "verified_at": VERIFIED_AT,
        "gateways": len(g),
        "gateway_endpoints": sum(len(x.get("endpoints", [])) for x in g),
        "relays": len(RELAYS),
        "relays_with_checkin": len([x for x in RELAYS if x.get("checkin_path")]),
        "official": len(OFFICIAL),
        "official_cn": len([x for x in OFFICIAL if x["region"] == "国内"]),
        "official_intl": len([x for x in OFFICIAL if x["region"] == "海外"]),
        "open_source": len(OPEN_SOURCE),
        "vibe_proxy": len(VIBE_PROXY),
        "vibe_proxy_with_checkin": len([x for x in VIBE_PROXY if x.get("checkin")]),
        "vibe_proxy_deployed": len([x for x in VIBE_PROXY if x.get("endpoint")]),
        "vibe_dead": len(VIBE_DEAD),
        "total_upstreams": len(all_upstreams()),
        "codebuddy_models": len(CODEBUDDY_MODELS),
    }
